apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expenses
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expenses
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: backend
        image: ghcr.io/your-org/your-repo/backend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/expenses"
        - name: UPLOAD_PATH
          value: "./uploads"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq-service"
        - name: RABBITMQ_VHOST
          value: "/"
        - name: RABBITMQ_EXCHANGE
          value: "expenses_exchange"
        - name: JWT_SECRET
          value: "expenses-secret-key-2024"
        volumeMounts:
        - name: auth-config
          mountPath: /app/auth.json
          subPath: auth.json
        - name: uploads
          mountPath: /app/uploads
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: auth-config
        configMap:
          name: backend-auth
      - name: uploads
        emptyDir: {}