apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: expenses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: processor
        image: ghcr.io/your-org/your-repo/processor:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          exec:
            command: ["python", "-c", "import pika; exit(0)"]
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq-service"
        - name: RABBITMQ_VHOST
          value: "/"
        - name: RABBITMQ_EXCHANGE
          value: "expenses_exchange"
        - name: OUTPUT_FOLDER
          value: "/app/messages"
        volumeMounts:
        - name: messages
          mountPath: /app/messages
      volumes:
      - name: messages
        emptyDir: {}