apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount | default .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Values.global.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
        volumeMounts:
        - name: frontend-config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
        readinessProbe:
{{ toYaml .Values.frontend.readinessProbe | indent 10 }}
      volumes:
      - name: frontend-config
        configMap:
          name: frontend-config
