name: Security Analysis

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python, csharp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  container-security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend, processor, lakepublisher]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t ${{ matrix.service }}:test ./packages/${{ matrix.service }} --target production

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.service }}:test
          format: sarif
          output: trivy-${{ matrix.service }}.sarif

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ matrix.service }}.sarif
          category: container-${{ matrix.service }}

  kubernetes-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Run Checkov scan on K8s manifests
        uses: bridgecrewio/checkov-action@master
        with:
          directory: devops/kubernetes
          framework: kubernetes
          output_format: sarif
          output_file_path: checkov-k8s.sarif

      - name: Run Helm security scan
        run: |
          # Template Helm chart and scan with Checkov
          helm template expenses devops/helm/sampleproject > helm-templated.yaml
          pip install checkov
          checkov -f helm-templated.yaml --framework kubernetes --output sarif --output-file-path checkov-helm.sarif || true

      - name: Upload Checkov scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-k8s.sarif
          category: kubernetes-manifests
        if: always()

      - name: Upload Helm scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-helm.sarif
          category: helm-chart
        if: always()

      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-security-results
          path: checkov-*.sarif
        if: always()

  security-summary:
    runs-on: ubuntu-latest
    needs: [static-analysis, container-security, kubernetes-security]
    if: always()
    steps:
      - name: Security Summary
        run: |
          echo "## 🔒 Security Analysis Summary" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Static Code Analysis (CodeQL)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Container Vulnerability Scanning (Trivy)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Kubernetes Security Analysis (Kubesec)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check the Security tab for detailed findings." >> $GITHUB_STEP_SUMMARY